# Generated by Django 4.2 on 2023-09-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asha_Info',
            fields=[
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('phone', models.BigIntegerField(primary_key=True, serialize=False)),
                ('village', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
