# Generated by Django 4.2 on 2023-09-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Info',
            fields=[
                ('doc_id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('doc_pass', models.TextField()),
                ('doc_name', models.TextField()),
                ('doc_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('doc_phn', models.IntegerField(max_length=10, unique=True)),
                ('doc_area', models.TextField()),
                ('doc_hosp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_SI', models.DateTimeField()),
                ('doc_SO', models.DateTimeField()),
                ('doc_att', models.IntegerField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor_info')),
            ],
        ),
    ]
