# Generated by Django 4.2 on 2023-09-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_alter_doctor_info_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_Asha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.TextField()),
                ('phone_patient', models.BigIntegerField()),
                ('village', models.TextField()),
                ('prescription', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
